server:
  port: 8010
spring:
  application:
    name: spring-cloud-demo-hystrix
feign:
  hystrix:
    enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaulfZone: http://localhost:8761/eureka
