server:
  port: 8082
spring:
  application:
    name: spring-cloud-demo-user-provider
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
