server:
  port: 8006
spring:
  application:
    name: spring-cloud-demo-config-client
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 172.16.63.128
    port: 5672
    username: admin
    password: 123456
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:9906/eureka

management:
  security:
    enabled: false
