spring:
  application:
    name: demo-zuul

server:
  host: 192.168.11.246
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  # 需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Orign
  ignored-headers: Access-Control-Allow-Orign,H-APP-Id,APPToken
  routes:
    apis1:
      path: /api1/**
      serviceId: demo-eureka
      url: https://blog.csdn.net/
    apis2:
      path: //huanzi833/**
      url: https://blog.csdn.net/

ribbon:
  # 设置路由转发请求的时候，创建请求连接的超时时间
  readTimeout: 3000
  # 用来设置路由转发请求的超时时间
  connectedTimeout: 6000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 设置API网关中路由转发请求的HystrixCommand执行超时时间
            timeoutInMilliseconds: 6000